### PR TITLE
Update protobuf requirement

### PR DESCRIPTION
**Pull request by theychx**
Here ya go (for #142)

### CODE REVIEW

**Comment by balloob** [comment]
We should require at least version 3.0 but no longer any beta's. We will also have to recompile the proto files to Python, in case some breaking changes sneaked in after beta 2.

**Comment by theychx** [comment]
> We will also have to recompile the proto files to Python

I need some instructions with this

**Comment by armills** [comment]
There are instructions here: https://developers.google.com/protocol-buffers/docs/pythontutorial#compiling-your-protocol-buffers

The three .proto files in chromecast_protobuf need to be compiled into the three *_pb2.py files in pychromecast.

**Comment by theychx** [comment]
The proto files have been updated in the chromium git repo, since they were imported to [chromecast_protobuf](../tree/master/chromecast_protobuf). Should I update those before proceeding? Also, I plan using protoc 3.1.0 (the pre-compiled version from the google github repo). Let me know if you want me to use 3.0.0, or whatever.

**Comment by armills** [comment]
Try updating to the latest proto files from chromium. It looks like they've only added new optional features, so nothing should break. Make sure you test the library as well as you can after the change.

It's probably safest to use protoc 3.0.0, but it shouldn't make a difference.

**Comment by theychx** [comment]
I have run [/examples/non_blocking.py](../blob/master/examples/non_blocking.py) without problems and also done some casual `media_controller` tests myself. I am really not super familiar with pychromecast, so if you have some additional tests/examples you want me to run, I'll be happy to do that.

The files generated by `protoc 3.0.0` and `protoc 3.1.0` are identical.

**Comment by balloob** [comment]
Awesome, thanks!

**Pull request merged**
