### PR TITLE
Add support for listening for media load errors. Resolve #54

### LINKED ISSUE #54: MediaController should handle load error
2015-07-30 14:40:01,890 - pychromecast.socket_client - WARNING - Message unhandled: Message urn:x-cast:com.google.cast.media from web-25 to sender-0: {u'type': u'LOAD_FAILED', u'requestId': 1538}

Easily reproducable by sending a URL that is non existing. It would be nice to be able to listen for these in the standard controller.

### PR DESCRIPTION
**Pull request by noob-4-life**

### CODE REVIEW

**Comment by noob-4-life** [comment]
The build error is due to pylint's 'too-many-public-methods'. Fixed with
```python
# pylint: disable=too-many-public-methods
def __init__(self):
    super(MediaController, self).__init__(
        "urn:x-cast:com.google.cast.media")
```
But I'm not sure if it's cool to ignore this error or if it would be better to try a different implementation?

**Comment by balloob** [comment]
That's cool. Pylint can be a bit strict sometimes. I'm on the road now, can
have a look at it in a bit

**Comment by noob-4-life** [comment]
Alright sounds good, I'll go ahead and push the fixed commit so that it builds.

**Comment by balloob** [comment]
Sooo, this PR looks good but I totally forgot about it, sorry. If you could rebase it I'll be down to merge it.

**Comment by Hedda** [comment]
@balloob @noob-4-life any plans to rebase and merge this PR?

**Comment by balloob** [comment]
This PR seems to have gone stale. Closing it. You can reopen it when you're ready to finish it.

**Pull request closed without merging**
