### PR TITLE
Increased Windows Compatibility

### PR DESCRIPTION
**Pull request by rmkraus**
Windows protobuf descriptors don’t seem to accept the syntax argument.
Removing it seems to cause to issues. This update will remove the
syntax argument if it is not present in the FileDescriptor. It will
assume that if the syntax argument is not in one, then it is not any of
the Descriptors.

### CODE REVIEW

**Comment by rmkraus** [comment]
This PR is to address balloob/home-assistant#221.

**Comment by balloob** [comment]
Were you running [Protobuf 3.0.0a3](https://pypi.python.org/pypi/protobuf/3.0.0a3) ? 

The file you adjusted has been automatically generated by 3.0.0a3 and should be compatible with it.

**Comment by rmkraus** [comment]
Please do not power off or unplug your machine. Installing update....

I'll let you know whenever my Windows machine comes back online. I want to say it was 3.0.0a1. It might be worth noting that this is the version that installed when I ran the requirements.txt from home-assistant through pip. I haven't traced through to figure out why.

**Comment by rmkraus** [comment]
pip install --upgrade pychromecast
and everything works correctly. So the real problem is that the incorrect version of pychromecast was installed by HA. Looks like I barked down the wrong tree on this one. My bad.

**Comment by balloob** [comment]
[You're not alone](https://github.com/balloob/pychromecast/issues/47#issuecomment-107822162)

**Comment by rmkraus** [comment]
Ahh. I see. Maybe there should be a pip requirement for pychromecast then?

**Comment by balloob** [comment]
Well [setup.py](https://github.com/balloob/pychromecast/blob/master/setup.py) should ensure that the dependencies get installed when installing PyChromecast. Somehow older versions of pip interpret the versions wrong.

**Comment by rmkraus** [comment]
Sorry, I wasn't clear. I meant to put install_requires=['pip>=xxx', ....] to setup.py. Although that won't work because it would update pip for the next run (if it even works at all). So it may be worth noting that this patch would fix pychromecast when it is installed with older version of pip. So that's something.

**Comment by balloob** [comment]
It's in the [PyChromecast README](https://github.com/balloob/pychromecast#dependencies) but HA users won't read it

**Comment by rmkraus** [comment]
haha, yeah, case in point

**Pull request closed without merging**
