### PR TITLE
Fix launch callback function

### PR DESCRIPTION
**Pull request by balloob**
Attempt at trying to fix the launch callback function. @madmod, can you verify that this works for your PR?

### CODE REVIEW

**Comment by madmod** [comment]
Unfortunately this doesn't work. It does work if the `self.launch` call is not the last thing in the thread. (I added a `time.sleep(10)` after my call to `self.launch`.)

**Comment by madmod** [comment]
I've fixed this in #184 since that seems more efficient than suggesting changes to this PR.

**Comment by balloob** [comment]
What do you mean with last thing in the thread, do you mean last thing in the script?

**Comment by madmod** [comment]
Yeah I meant script. Specifically I tested this by adding those lines to the end of `examples/dashcast_blocking.py`. (Unrelated to the debugging `time.sleep` I currently have in that file for catching any responses from the DashCast receiver. It now works all the time.)

**Comment by balloob** [comment]
Closing this as fix included in #184

**Pull request closed without merging**
