### PR TITLE
Spotify authorization Code Flow

### PR DESCRIPTION
**Pull request by SamuelPoggioli**
Remove spotify-token usage and add Spotify authorization Code Flow
This token acquisition method is less easy to use but it is more robust.

### CODE REVIEW

**Comment by balloob** [comment]
@enriquegh is this ok?

**Comment by enriquegh** [comment]
last time I tried getting a token from spotipy this didn't work.
It seems that the access token doesn't have enough permissions to start the Spotify session on Chromecast.

Did this work for you @SamuelPoggioli ?
Let me give this a shot, maybe something changed there since I last did this.

**Comment by SamuelPoggioli** [comment]
If you use the "Client Credentials Flow" method, the token does not have the necessary privileges but I use the "Authorization Code Flow" method which has all the necessary privileges (the "SCOPE" variable defines the desired privileges).

The problem with this method is that on first use, the script must use the web browser to request a usage token (a other...). Spotify asks to validate the application and returns the usage token in the URL's GET parameters. 

The credentials are cached locally and are used to automatically re-authorized expired tokens.

**Comment by Nojahhh** [comment]
Any progress regarding this issue?

**Comment by emontnemery** [comment]
@fondberg I don't think this is needed, #275 should be enough?

**Comment by Nojahhh** [comment]
Can confirm. #275 solved it for me. 
Thanks a lot @fondberg and @emontnemery.

**Comment by fondberg** [comment]
I don't think this is needed in the short term and I believe it has a flaw in that it requires a user confirm which is not so easy in a backend solution.

For the future when spotify adds more oauth realms we can switch to that. In the meantime I believe impersonating a browser which spotipy does is ok

**Comment by emontnemery** [comment]
Closing in favour of #275.

**Pull request closed without merging**
